### ISSUE TITLE
vue文件的style标签中增加backgroud image 应该如何配置呢?

### ISSUE THREAD

**Issue by hevily** [adouwt/vue-cli3-admin-system#1]
xxx.vue

<style lang="scss">
body{
background:ulr(xxxxx.jpg) //这个如何配置才能生效呢?
}
</style>

**Comment by adouwt** [comment]
<style lang="scss">
  body {
    background-image: url('../../assets/404_images/404.png');
  }
</style>
注意：在组件中 不能添加 scoped 属性，不然，不生效，如下面：
<style lang="scss" scoped>
  body {
    background-image: url('../../assets/404_images/404.png');
  }
</style>
